name: spoke-genelab 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10
  - jupyterlab
  - jupyterlab_widgets
  - ipywidgets
  - pandas
  - tqdm
  - matplotlib
  - seaborn
  - black
  - pylint
  - vulture
  - papermill
  - monotonic=1.5
  - python-dotenv=1.0.0
  - openjdk=17.0.8
  - ipycytoscape
  - inflection
  - pip
  - pip:
     - py2neo==2021.2.4
     - neobolt


